---
- name: Include  variables.
  include_vars: main.yaml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

# install sudo
- include_tasks: sudo_Debian.yaml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: sudo_RedHat.yaml
  when:
    - ansible_os_family == 'RedHat'

# create acu user
- name: create ansible user
  user:
    name: "{{ acu_user }}"
    password: "{{ acu_passwd }}"
    groups: "{{ acu_groups }}"
    shell: /bin/bash
    system: no
    createhome: yes
    state: present

- name: register ansible users ssh key
  authorized_key:
    user: "{{acu_user}}"
    state: present
    key: "{{ lookup('file', acu_pubkeyfile) }}"
    manage_dir: yes

# set ansible user sudo
- name: add ansible user to sudo
  template:
    src: sudousr
    dest: "/etc/sudoers.d/sudo{{ acu_user }}"
    owner: root
    group: root
    mode: "u=rw,g=,o="
